/*********************************************
 * AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * 2014-02-23 13:23:07.605406
 *
 * This file was automatically generated by the 'shader_compiler.py' script
 * It should not be modified by hand.
 *********************************************/


#ifndef WT_COMPILEDSHADERS_H
#define WT_COMPILEDSHADERS_H

namespace wt
{

const char* getShaderSource(const char* uri);

} // </wt>

#endif // </WT_COMPILEDSHADERS_H>
